sudo: false
language: node_js

node_js:
  - "stable"

  cache:
    directories:
      - 'node_modules'

service:
  - postgresql

env:
  global:
    - NODE_ENV=test
    - JWT_SECRET=prfdndn

before_script:
  - psql -c 'drop database if exists test_wayfarer;' -U postgres
  - psql -c 'create database wayfarer;' -U postgres
  - psql -c "CREATE USER ticobrahe WITH PASSWORD wayfarer;" -U postgres
  - npm run migrate

script:
  - npm rum test
