sudo: false
language: node_js

node_js:
  - "stable"

cache:
  directories:
    - 'node_modules'

service:
  - postgresql

env:
  global:
    - JWT_SECRET=jdkksdidjijijirbrg

script:
  - npm rum test

after_success:
  - npm run coverage
