sudo: false
language: node_js

node_js:
  - "stable"

cache:
  directories:
    - 'node_modules'

service:
  - postgresql

env:
  global:
    - TEST_DATABASE_URL=postgres://ticobrahe:wayfarer@127.0.0.1:5432/test_database
    - NODE_ENV=test
    - JWT_SECRET=prfdndn

before_script:
  - psql -c 'drop database if exists test_database;' -U postgres
  - psql -c 'create database test_database;' -U postgres
  - npm run migrate

script:
  - npm rum test

after_success:
  - npm run coverage
