sudo: false
language: node_js

node_js:
  - "stable"

cache:
  directories:
    - 'node_modules'

service:
  - postgresql

env:
  global:
    - JWT_SECRET=prfdndn

before_script:
  - psql -c 'drop database if exists hcnilwkw;' -U postgres
  - psql -c 'create database hcnilwkw;' -U postgres
  - npm run migrate

script:
  - npm rum test

after_success:
  - npm run coverage
